# Generated by Django 3.2.9 on 2023-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20230212_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RU'), ('us', 'USD')], default='ru', max_length=2),
        ),
    ]
