# Generated by Django 3.2.9 on 2023-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RU'), ('us', 'USD')], default='rub', max_length=3),
        ),
    ]
