# Generated by Django 3.2.9 on 2023-02-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(null=True, to='payments.Item'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
