# Generated by Django 3.2.9 on 2023-02-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20230213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='number',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='tax',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='payments.order'),
        ),
    ]
