version: "3.9"

services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
    - 8000:8000
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - "./postgres:/var/lib/postgresql/data"
